title: Kennesaw State University Football Booster
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://<your-github-username>.github.io"  # the base hostname & protocol for your site
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the official page of the KSU Football Booster Club.

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
